version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: node:10.12.0

jobs:
  test:
    <<: *defaults  
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-
          - v1-dependencies-

      - run: npm install
      - run:
          name: Run linter
          command: npm run lint
      - run:
          name: Run tests
          command: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Check version and publish
          command: .circleci/version_check.sh
            
workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
              branches:
                  ignore:
                      - master
      - deploy:
          filters:
            branches:
                only: 
                    - master
